environment:
  domain: "dockerlab.local"
  base_box: "frjaraur/xenial64"
  base_box_version: "1.4"
  engine_version: "17.03.2~ce-0~ubuntu-xenial"

boxes:
- name: "k8s-node1"
  role: "worker"
  mgmt_ip: "10.10.10.12"
  hostonly_ip: "192.168.56.12"
  mem: "1524"
  cpu: "1"

- name: "k8s-node2"
  role: "worker"
  mgmt_ip: "10.10.10.13"
  hostonly_ip: "192.168.56.13"
  mem: "1524"
  cpu: "1"
#
#- name: "k8s-node3"
#  role: "worker"
#  mgmt_ip: "10.10.10.14"
#  hostonly_ip: "192.168.56.14"
#  mem: "1524"
#  cpu: "1"

- name: "k8s-master1"
  role: "master"
  mgmt_ip: "10.10.10.11"
  hostonly_ip: "192.168.56.11"
  mem: "3072"
  cpu: "2"